hyperjumptech/hyperjump.tech

app/(smdd)/smdd2024/[lang]/projects.tsx
app/(smdd)/smdd2024/components/hero.tsx
app/components/case-studies.tsx
app/components/faqs.tsx
app/components/footer.tsx
app/components/grid-items.tsx
app/components/nav.tsx
app/components/services.tsx
app/components/sticky-nav-main.tsx
app/components/sticky-nav.tsx

Fix: Landing page

---

app/(main)/page.tsx
app/components/footer.tsx
app/components/nav.tsx
bun.lock
data.json
package.json

Feat: Add Open Graph and JSON-LD

---

app/(smdd)/smdd2024/[lang]/nav.tsx
app/components/grid-items.tsx

Fix : FIxing color hyperjump page

---

.github/workflows/deploy.yml

This PR fixes #16, as a followup 
- Expose the variables for NEXT_PUBLIC_AI_AGENT_URL
1. Deploy the app
N/A
Might need to set NEXT_PUBLIC_AI_AGENT_URL to the variables

Fix: Expose NEXT_PUBLIC_AI_AGENT_URL

---

app/(services)/services/[lang]/home.tsx
app/(services)/services/components/service-card.tsx
app/components/nav.tsx
package-lock.json

https://github.com/user-attachments/assets/2c92c24f-422d-403e-a656-4429ac5d0f67

Fix: Unhide "See More" button on services page

---

app/(inferenceai)/inferenceai/[lang]/home.tsx
app/(inferenceai)/inferenceai/rag-chatbot/[lang]/home.tsx
app/components/grid-items.tsx
app/globals.css

Update design Inference AI & RAG Chatbot

---

app/(inferenceai)/inferenceai/[lang]/home.tsx
app/(inferenceai)/inferenceai/rag-chatbot/[lang]/home.tsx
app/components/grid-items.tsx

Fix: Fix faq accordion

---

app/components/ai-agent.tsx

This PR allows submit on enter for AI Agent Chat
1. Added keydown event
1. When AI UI displayed, select any option
2. Press enter
3. It should submit the form
https://github.com/user-attachments/assets/56ecd258-36cb-4b94-b195-e177c1e2570b

Fix: Submit AI Agent question on enter

---

app/(services)/services/cto-as-a-service/[lang]/home.tsx
app/(services)/services/erp-implementation/[lang]/home.tsx
app/(services)/services/software-as-a-service/[lang]/home.tsx
app/(services)/services/tech-due-diligence/[lang]/home.tsx

Fix: Fix the content alignment on the service detail page

---

app/components/ai-agent.tsx

This PR adds minimize button above the AI UI floating div
- Added minimize button. When clicked, it will minimize and show "Ask HyperBot" button.
1. Open landing page
2. Click the minimize button
https://github.com/user-attachments/assets/253ba7c6-b733-49e2-b2d4-64b2a19691d4
- Added condition for the floating AI UI not to be displayed if the env is not set

Feat: Add minimize button to AI UI Landing Page Floating Div

---

app/(inferenceai)/inferenceai/components/language-picker.tsx
app/(inferenceai)/inferenceai/rag-chatbot/[lang]/language-picker.tsx
app/(main)/[lang]/language-picker.tsx

Fix: Update Language Picker to Flat Design in Safari

---

app/(case-studies)/case-studies/[lang]/layout.tsx
app/(case-studies)/case-studies/ctoaas-media/[lang]/layout.tsx
app/(case-studies)/case-studies/erp-fisheries/[lang]/layout.tsx
app/(main)/[lang]/layout.tsx
app/(services)/services/[lang]/layout.tsx
app/(services)/services/cto-as-a-service/[lang]/layout.tsx
app/(services)/services/erp-implementation/[lang]/layout.tsx
app/(services)/services/software-as-a-service/[lang]/layout.tsx
app/(services)/services/tech-due-diligence/[lang]/layout.tsx
app/components/clients.tsx

11739 - Fix the inconsistent logo position:
https://github.com/user-attachments/assets/fdd0088d-7b77-44f1-b3cc-1063ad3facc6
11743 -  Fix spacing in the services page:

Fix: Fix spacing in the services page

---

locales/en/messages.json
locales/id/messages.json

Fix: Replace Hyperjump in the footer with PT. Artha Rajamas Mandiri

---

.github/scripts/generate-redirect.js

Fix wrong redirect from / to /en

Fix: Wrong redirect

---

app/[lang]/(hyperjump)/components/nav.tsx
app/components/sticky-nav-main.tsx
app/page.tsx

https://github.com/user-attachments/assets/c83e0d9f-2ab9-4601-ab9b-08e1832f9c97
https://github.com/user-attachments/assets/a0e5b097-b218-41e2-bf5a-114dbe6a319e

Fix: Navbar styling

---

app/[lang]/(inferenceai)/inferenceai/components/nav.tsx
app/[lang]/(inferenceai)/inferenceai/data.ts
app/components/sticky-nav-main.tsx
bun.lock
components/ui/dropdown-menu.tsx
locales/en/inferenceai.json
locales/id/inferenceai.json
package.json

Feat: Add InferenceAI link to navbar

---

app/[lang]/(inferenceai)/inferenceai/[slug]/home.tsx
app/[lang]/(inferenceai)/inferenceai/[slug]/page.tsx
app/[lang]/(inferenceai)/inferenceai/data.ts
locales/en/inferenceai.json
locales/id/inferenceai.json

Presenton demo:
StartGPT demo:

Feat: Create a working demo for Presenton and StartGPT

---

app/[lang]/(inferenceai)/inferenceai/components/client-wrapper.tsx
app/[lang]/(inferenceai)/inferenceai/components/nav.tsx
app/[lang]/(inferenceai)/inferenceai/data.ts

Fix: Fix align solutions data between navbar and section

---

app/[lang]/(hyperjump)/case-studies/[slug]/page.tsx
app/[lang]/(hyperjump)/case-studies/page.tsx
app/[lang]/(hyperjump)/page.tsx
app/[lang]/(hyperjump)/services/[slug]/page.tsx
app/[lang]/(hyperjump)/services/page.tsx
app/layout.tsx
lib/default-metadata.ts

https://github.com/user-attachments/assets/a2b3f5c3-490f-4396-b9be-20db3cebaa9a

Fix: Fix incorrect Open Graph meta tags on all pages

---

app/[lang]/(hyperjump)/components/nav.tsx
locales/en/main.json
locales/id/main.json

Fix Rename Services to Our Services and Improve menu gap consistency

---

app/[lang]/(hyperjump)/components/nav.tsx
locales/en/ai.json
locales/id/ai.json

Remove Our Services dropdown:
Replace Inference AI short description :

Fix: Replace Inference AI short description and Remove Our Services dropdown

---

app/[lang]/(hyperjump)/components/nav.tsx

https://github.com/user-attachments/assets/1ad33879-339c-495c-9189-7c91cf3f6612

Fix: Remove download logo feature
